### ISSUE TITLE
Metro Theme causes crash on startup

### ISSUE THREAD

**Issue by leftofnull** [Slivo-fr/EveHQ#11]
After choosing the Metro Theme from the theme picker and relaunching the app you are met with:

*EveHQ Error Report*

EveHQ Version: 2.17.1.0
Date: 23/03/2015 19:36:51
Error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
----
\\{panel:title=StackTrace|borderStyle=dashed|bordercolor=#ccc|titleBGColor=#eee|bgColor=#eee}*****START Exception Details*****
Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Source: mscorlib
StackTrace:    at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)
   at DevComponents.DotNetBar.SubItemsCollection.get_Item(String name)
   at EveHQ.Forms.FrmEveHQ.frmEveHQ_Load(Object sender, EventArgs e) in C:\Workspace\EveHQ\EveHQ\Forms\frmEveHQ.vb:line 374
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevComponents.DotNetBar.RibbonForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevComponents.DotNetBar.RibbonForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
*****END Exception Details*****

========== Plug-ins ==========

EveHQ.HQF.dll (1.0.0.0)
EveHQ.KillMailViewer.dll (1.0.0.0)
EveHQ.Prism.dll (1.0.0.0)
EveHQ.Void.dll (1.0.0.0)

========= System Info =========

Operating System: Microsoft Windows NT 6.2.9200.0
.Net Framework Version: 4.0.30319.0
EveHQ Location: C:\Program Files (x86)\EveHQ
EveHQ Cache Locations: C:\Users\Alexander\AppData\Roaming\EveHQ
\\{panel}

**Comment by leftofnull** [comment]
Submitted a pull request with a fix
