### ISSUE TITLE
#System in Item Browser? - Crash Log

### ISSUE THREAD

**Issue by rouing** [Slivo-fr/EveHQ#62]
Screenshot Here
rouing/EveHQ/issues/1

*EveHQ Error Report*

EveHQ Version: 2.27.5.0
Date: 01/07/2016 19:37:45
Error: The given key was not present in the dictionary.
----
\\{panel:title=StackTrace|borderStyle=dashed|bordercolor=#ccc|titleBGColor=#eee|bgColor=#eee}*****START Exception Details*****
Message: The given key was not present in the dictionary.
Source: mscorlib
StackTrace:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EveHQ.Core.ItemBrowser.FrmIB.DisplayMaterials(Int32 itemID) in C:\Users\Guillaume\Documents\GitHub\EveHQ\EveHQ.Core\ItemBrowser\frmIB.vb:line 995
   at EveHQ.Core.ItemBrowser.FrmIB.DisplayItem(Int32 typeID, Boolean addToStack) in C:\Users\Guillaume\Documents\GitHub\EveHQ\EveHQ.Core\ItemBrowser\frmIB.vb:line 439
   at EveHQ.Core.ItemBrowser.FrmIB.adtBrowse_SelectionChanged(Object sender, EventArgs e) in C:\Users\Guillaume\Documents\GitHub\EveHQ\EveHQ.Core\ItemBrowser\frmIB.vb:line 293
   at DevComponents.AdvTree.AdvTree.OnSelectionChanged(EventArgs e)
   at DevComponents.AdvTree.AdvTree.SelectNode(Node node, eTreeAction action)
   at DevComponents.AdvTree.AdvTree.ٸ(Node ِ, MouseEventArgs ٜ, Point ٦)
   at DevComponents.AdvTree.AdvTree.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
*****END Exception Details*****

========== Plug-ins ==========

EveHQ.HQF.dll (1.0.0.0)
EveHQ.KillMailViewer.dll (1.0.0.0)
EveHQ.Prism.dll (1.0.0.0)
EveHQ.Void.dll (1.0.0.0)

========= System Info =========

Operating System: Microsoft Windows NT 6.2.9200.0
.Net Framework Version: 4.0.30319.42000
EveHQ Location: C:\Program Files (x86)\EveHQ
EveHQ Cache Locations: C:\Users\ardoinc\AppData\Roaming\EveHQ
\\{panel}

**Comment by Slivo-fr** [comment]
It may be related to the DB being outdated with Eve june patch.
Also, please join our forums for bug reporting, github ticket management will be disabled.
